version: '3.8'

services:
  # Conteneur PHP + Symfony
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://symfony:symfony@database:3306/symfony_db"

  # Conteneur MySQL
  database:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Conteneur Node pour Webpack + React
  node:
    image: node:18
    container_name: node_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["yarn", "dev"]

volumes:
  db_data:
